# ---------------- VISUALIZER ---------------- #
# VISUALIZER WINDOW DIMENSIONS
VISUALIZER_WIDTH = 1024
VISUALIZER_HEIGHT = 800


# COLOURS
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)

# BARS
INSPECTED_COLOUR = BLUE
COMPARED_COLOUR = RED
BASE_COLOUR = GREEN

# BUTTONS
BUTTON_WIDTH = VISUALIZER_WIDTH // 6
BUTTON_HEIGHT = 50
BUTTON_SPACING = 0
BUTTONS_FONT_SIZE = 24
BUTTONS_FONTS = "assets\\Ticketing.ttf"
BORDER_WIDTH = BUTTON_WIDTH // BUTTON_HEIGHT
# MENU
MENU_HEIGHT = BUTTON_HEIGHT * 2
MENU = (0, 0, BUTTON_WIDTH * 3,  MENU_HEIGHT)


# WINDOW
WINDOW_HEIGHT = VISUALIZER_HEIGHT + MENU_HEIGHT
FPS = 200

# ---------------- ALGORITHMS ---------------- #
ARRAY_SIZE = 1024
BAR_WIDTH = ARRAY_SIZE // VISUALIZER_WIDTH
